package com.example.log.dao;

import com.example.log.entity.TestGenerateMybatis;
import java.util.List;

public interface TestGenerateMybatisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generate_mybatis
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generate_mybatis
     *
     * @mbggenerated
     */
    int insert(TestGenerateMybatis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generate_mybatis
     *
     * @mbggenerated
     */
    TestGenerateMybatis selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generate_mybatis
     *
     * @mbggenerated
     */
    List<TestGenerateMybatis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generate_mybatis
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestGenerateMybatis record);
}