package com.example.log.dao;

import com.baomidou.mybatisplus.mapper.BaseMapper;
import com.example.log.entity.TestGenerateMybatis;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TestGenerateMybatisMapper extends BaseMapper<TestGenerateMybatis> {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table test_generate_mybatis
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Long id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table test_generate_mybatis
//     *
//     * @mbggenerated
//     */
//    int insert(TestGenerateMybatis record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table test_generate_mybatis
//     *
//     * @mbggenerated
//     */
//    TestGenerateMybatis selectByPrimaryKey(Long id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table test_generate_mybatis
//     *
//     * @mbggenerated
//     */
//    List<TestGenerateMybatis> selectAll();
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table test_generate_mybatis
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(TestGenerateMybatis record);
}